# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_iris": "00_random_forest.ipynb",
         "rf_model_class": "00_random_forest.ipynb",
         "y_pred_rf_class": "00_random_forest.ipynb"}

modules = ["radom_forest.py"]

doc_url = "https://M-Fleischer.github.io/RNN_Example_1/"

git_url = "https://github.com/M-Fleischer/RNN_Example_1/tree/{branch}/"

def custom_doc_links(name): return None
